name: Install using pip
run-name: Install using pip
on: 
  push:
  pull_request:
  workflow_dispatch:
jobs:
  install-and-run:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']
      fail-fast: false
    continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install abogen
        run: python -m pip install abogen
      #- name: Run abogen
      #  run: abogen
